/* --- Output generated by lang compiler. Do Not Edit --- */
#include "lang_runtime.h"
#include <stddef.h>
#include <stdint.h>

/* --- Class Struct Declarations --- */
struct __Person;
typedef struct __Person __Person;
struct __Person_vtable;
struct __Person_array_type {
	unsigned int len;
	__Person** vals;
};

/* --- Class Struct Definitions --- */
struct __Person {
	struct __Person_vtable* _vtable;
	struct __char_array_type* name;
	int age;
};
struct __Person_vtable {
	struct vtable_head _header;
	struct __char_array_type* (*getName)(void*);
	int (*addToAge)(void*, int);
};

/* --- Function Headers --- */
struct __char_array_type* __Person_getName(void * _data);
int __Person_addToAge(void * _data, int inc);
void __main(void * _data);
/* --- Program Body --- */
int __a = 0;
int __global;
struct __char_array_type* __Person_getName(void *_data) {
return ((__Person*) _data)->name;
}

int __Person_addToAge(void *_data, int inc) {
void res = ;
char num = 6;
return 5;
}

void __main(void *_data) {
}

void main (int argc, char **argv) {
__global = __a;
__main();
};
