/* --- Output generated by lang compiler. Do Not Edit --- */
#include "lang_runtime.h"
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

/* --- Class Struct Declarations --- */
struct __Super;
typedef struct __Super __Super;
struct __Super_vtable;
struct __Child;
typedef struct __Child __Child;
struct __Child_vtable;
/* --- Class Struct Definitions --- */
struct __Super {
	struct __Super_vtable* _vtable;
	struct array_type* array;
	int v1;
};
struct __Super_vtable {
	struct vtable_head _header;
};

struct __Child {
	__Super _super;
	long v2;
};
struct __Child_vtable {
	struct __Super_vtable _vtable_super;
};

/* --- Function Headers --- */
bool __sum(void * _data, int a, int b);
void __main(void * _data);
/* --- Program Body --- */
int __arg;
char __test;
bool __sum(void *_data, int a, int b) {
return (((!((a==b))))&&(a));
}

void __main(void *_data) {
__Child* p = NULL;
bool b = (p != NULL);
}

void main (int argc, char **argv) {
__arg = (int)5;
__test = (char)'a';
__main(NULL);
};
