/* --- Output generated by lang compiler. Do Not Edit --- */
#include "lang_runtime.h"

/* --- Class Struct Declarations --- */
struct __Person;
typedef struct __Person __Person;
struct __Person_vtable;
struct __Person_array_type {
	unsigned int len;
	__Person** vals;
};

/* --- Class Struct Definitions --- */
struct __Person {
	struct __Person_vtable* _vtable;
	struct __char_array_type* name;
	int age;
};
struct __Person_vtable {
	struct vtable_head _header;
	void (*setName)(void*, int);
	struct __char_array_type* (*getName)(void*);
};

/* --- Function Headers --- */
struct __char_array_type* __Person_getName(void * _data);
void __Person_setName(void * _data, int i);
void __main(void * _data);
/* --- Program Body --- */
struct __char_array_type* __Person_getName(void *_data) {
return ((Person*) _data)->name;
}

void __Person_setName(void *_data, int i) {
}

void __main(void *_data) {
}

