/* --- Output generated by lang compiler. Do Not Edit --- */
#include "core/core.h"

/* --- Class Struct Declarations --- */
/* --- Class Struct Declarations --- */
/* --- Class Struct Declarations --- */
struct __a__b__obj;
struct __a__b__obj_vtable;
/* --- Class Struct Definitions --- */
struct __a__b__obj {
	struct __a__b__obj_vtable* _vtable;
};
struct __a__b__obj_vtable {
	struct _lang_vtable_head _header;
};

/* --- Class Struct Declarations --- */
/* --- Class Struct Definitions --- */
/* --- Class Struct Definitions --- */
/* --- Class Struct Declarations --- */
/* --- Class Struct Definitions --- */
/* --- Class Struct Definitions --- */
/* --- Function Headers --- */
void __a__b__obj_construct(void *, int);
struct __a__b__obj* __a__b__obj(void *, int);
void __main(void *);
/* --- Class VTable Instances --- */
extern struct __a__b__obj_vtable __a__b__obj_vtable_inst;

struct __a__b__obj_vtable __a__b__obj_vtable_inst = {
._header = {
/* TODO: gc_desk */
.parent_vtable = NULL,
},
};
/* --- Program Body --- */
int __a__b__test;
void __a__b__obj_construct(void *_data, int a) {
}

struct __a__b__obj* __a__b__obj(void * _data, int arg0) {
struct __a__b__obj* _obj = _lang_gc_alloc(sizeof(struct __a__b__obj));
((struct __Object *)_obj)->_vtable = (struct __Object_vtable *)&__a__b__obj_vtable_inst;
__a__b__obj_construct(_obj,  arg0);
return _obj;
}

struct __a__b__obj* __a__c__o;
int __b__test;
void __main(void *_data) {
}

int main (int argc, char **argv) {
__a__b__test = (int)(7);
__a__c__o = (struct __a__b__obj*)(__a__b__obj(NULL, (int)(5));
__b__test = (int)(5);
__main(NULL);
};
