/* --- Output generated by lang compiler. Do Not Edit --- */
#include "core/core.h"

/* --- Class Struct Declarations --- */
/* --- Class Struct Definitions --- */
/* --- Function Headers --- */
void __print(void *, _lang_array*);
void __putc(void *, char);
void __printNumber(void *, long);
_lang_array* __readLine(void *);
void __main(void *, _lang_array*, int);
/* --- Class VTable Instances --- */

/* --- Program Body --- */
void __main(void *_data, _lang_array* argc, int argv) {
long a = (long)(1);
long b = (long)((2+1));
__print(NULL, (_lang_array*)(_lang_make_string("hello")));
}

int main (int argc, char **argv) {
__main(NULL);
};
