/* --- Output generated by lang compiler. Do Not Edit --- */
#include "core/core.h"

struct __io__File;
struct __io__File_vtable;
extern struct __io__File_vtable __io__File_vtable_inst;
struct __Object {
	struct __Object_vtable* _vtable;
};
struct __Object_vtable {
	struct _lang_vtable_head _header;
	void (*destruct)(void*);
	bool (*_op_equals)(void*, struct __Object*);
	long (*to_hash)(void*);
	_lang_array* (*to_string)(void*);
};

struct __io__File {
	struct __Object _super;
	struct __Object* _cfile;
};
struct __io__File_vtable {
	struct __Object_vtable _vtable_super;
	void (*putc)(void*, char);
	void (*print)(void*, _lang_array*);
	void (*println)(void*, _lang_array*);
	_lang_array* (*read)(void*, long);
	void (*flush)(void*);
	char (*getc)(void*);
	_lang_array* (*readln)(void*);
	void (*close)(void*);
};

struct __Object;
struct __Object_vtable;
extern struct __Object_vtable __Object_vtable_inst;
void __Object_construct(void *);
void __Object_destruct(void *);
long __Object_to_hash(void *);
_lang_array* __Object_to_string(void *);
bool __Object__op_equals(void *, struct __Object*);
struct __Object* __Object(void *);
void __io__File_construct(void *, _lang_array*, _lang_array*);
void __io__File_destruct(void *);
void __io__File_putc(void *, char);
void __io__File_print(void *, _lang_array*);
void __io__File_println(void *, _lang_array*);
char __io__File_getc(void *);
_lang_array* __io__File_read(void *, long);
_lang_array* __io__File_readln(void *);
void __io__File_flush(void *);
void __io__File_close(void *);
_lang_array* __io__File_to_string(void *);
struct __io__File* __io__File(void *, _lang_array*, _lang_array*);
extern const struct __io__File* __io__stdout;
extern const struct __io__File* __io__stdin;
extern const struct __io__File* __io__stderr;
void __main(void *);
void __main(void *_data) {
(_lang_temp_this = (__io__stdout), ((struct __io__File_vtable *)(((struct __Object *)_lang_temp_this)->_vtable))->print(_lang_temp_this, (_lang_array*)(_lang_make_string("Hello, World!"))));
_lang_array* s = (_lang_array*)((_lang_temp_this = (__io__stdin), ((struct __io__File_vtable *)(((struct __Object *)_lang_temp_this)->_vtable))->read(_lang_temp_this, (long)(10))));
(_lang_temp_this = (__io__stdout), ((struct __io__File_vtable *)(((struct __Object *)_lang_temp_this)->_vtable))->print(_lang_temp_this, (_lang_array*)(s)));
}

int main (int argc, char **argv) {
_lang_init();
__main(NULL);
};
