/* --- Output generated by lang compiler. Do Not Edit --- */
#include "core.h"

/* --- Class Struct Declarations --- */
/* --- Class Struct Definitions --- */
/* --- Function Headers --- */
void __print(void *, _lang_array*);
_lang_array* __readLine(void *);
void __main(void *);
/* --- Program Body --- */
void __main(void *_data) {
}

int main (int argc, char **argv) {
__main(NULL);
};
